In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.3.3

In [3]:
#Series
s=pd.Series()
s

Series([], dtype: object)

In [4]:
import numpy as np
import pandas as pd
data=np.array(['a','b','c','d'])
s=pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object

In [5]:
data=np.array(["a","b","c","d"])
s=pd.Series(data,index=[100,101,102,103])
print(s)

100    a
101    b
102    c
103    d
dtype: object

In [6]:
#Dict Series
data={"a":1.1,"b":2.2,"c":3,"d":"age"}
s=pd.Series(data)
print(s)

a    1.1
b    2.2
c      3
d    age
dtype: object

In [7]:
data={"a":1,"b":2,"c":3}
s=pd.Series(data,index=["a","d","b","c"])
print(s)

a    1.0
d    NaN
b    2.0
c    3.0
dtype: float64

In [12]:
#INDEXING AND SLICING
s=pd.Series([1,2,3,4,5])
i=s[1]
print(i)

print(s[0:4])

2
0    1
1    2
2    3
3    4
dtype: int64

In [20]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s['d'])
print(s['b'])
print(s['b':'e'])
print(s[['a','c','e']])

4
2
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
e    5
dtype: int64

In [22]:
#Creating an empty DataFrame
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [23]:
data=[1,2,3,4,5]
df=pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [24]:
#Creating a DataFrame from a Dict of list
data={'Name':['a','b','c','d'],
     'Age':[20,21,22,23]}
df=pd.DataFrame(data)
print(df)

  Name  Age
0    a   20
1    b   21
2    c   22
3    d   23

In [25]:
d={'one':pd.Series([1,2,3],index=['a','b','c']),
'Two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(d)
print(df)

   one  Two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [29]:
#Select a single column
d={'one':pd.Series([1,2,3],index=['a','b','c']),
'Two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(d)
print(df['one'])
print(df[['one','Two']])

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64
   one  Two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [37]:
d={'One':pd.Series([1,2,3],index=['A','B','C']),
'Two':pd.Series([1,2,3,4],index=['A','B','C','D'])}
df=pd.DataFrame(d)
#ADDING A NEW COLUMN BY PASSING SERIES
df['Three']=pd.Series([10,20,30],index=['A','B','C'])
df

   One  Two  Three
A  1.0    1   10.0
B  2.0    2   20.0
C  3.0    3   30.0
D  NaN    4    NaN

In [42]:
#Creating a table using random values
from numpy.random import randn
df=pd.DataFrame(randn(5,5,),index='A B C D E'.split(),columns='V W X Y Z'.split())
df

          V         W         X         Y         Z
A  0.568018 -0.919178 -0.242213  2.626956 -0.758931
B  0.068933 -0.548377 -0.833942 -1.458036  1.189173
C  0.147588 -0.648062 -0.499314 -1.623517 -1.407618
D -0.942188 -0.650009 -0.151601 -1.057737 -0.663683
E  0.222955  0.737079  0.241983 -1.631631 -0.014249

In [72]:
from numpy.random import randn
df=pd.DataFrame(randn(5,5,),index='A B C D E'.split(),columns='V W X Y Z'.split())
print(df)
#Take the rows of the table 
r1=df.loc['B']      #Lable Based(loc)
print("\n-------------\n",r1)
r2=df.iloc[2]
print(r2)

rc1=df.loc[['A','B'],['W','Y']]
rc1

          V         W         X         Y         Z
A  0.530828  0.322562  0.436138  1.327361  0.329311
B -0.673002  1.868806 -1.600764 -0.605446  0.564490
C  1.580839  0.658029  0.744191 -1.490222 -0.572122
D -0.235466 -1.194824 -0.047602  0.153240 -0.620504
E -0.397628 -0.660836  1.553281  1.131053 -0.740083

-------------
 V   -0.673002
W    1.868806
X   -1.600764
Y   -0.605446
Z    0.564490
Name: B, dtype: float64
V    1.580839
W    0.658029
X    0.744191
Y   -1.490222
Z   -0.572122
Name: C, dtype: float64

          W         Y
A  0.322562  1.327361
B  1.868806 -0.605446